#<<<<<<< Search
# Generated by Django 4.0.2 on 2022-02-25 21:00

from django.db import migrations, models
#=======
# Generated by Django 3.2.8 on 2022-03-03 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
#>>>>>>> main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#<<<<<<< Search
                ('name', models.CharField(max_length=1023)),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Admin')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
#=======
                ('userName', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Admin')])),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('gameMode', models.IntegerField(choices=[(0, 'Casual'), (1, 'Competitive')])),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 3, 3, 19, 11, 39, 906933, tzinfo=utc))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smg_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smg_app.account')),
#>>>>>>> main
            ],
        ),
    ]
