# Generated by Django 4.0.2 on 2022-03-08 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='gameMode',
            field=models.IntegerField(choices=[(0, 'Casual'), (1, 'Competitive')], default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='userName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
