# Generated by Django 4.0.2 on 2022-03-04 06:02

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gameStyle',
            field=models.IntegerField(choices=[(0, 'Casual'), (1, 'Competitive')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
