# Generated by Django 4.0.2 on 2022-03-13 22:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='games',
            name='account',
        ),
        migrations.RemoveField(
            model_name='games',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='gameStyle',
            field=models.TextField(choices=[('Casual', 'Casual'), ('Competitive', 'Competitive')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MOBA', 'MOBA'), ('Shooters', 'Shooters'), ('Platformer', 'Platformer'), ('RPG', 'RPG'), ('Action-adventure', 'Action-adventure'), ('RTS', 'RTS'), ('Puzzles', 'Puzzles'), ('ParyGames', 'ParyGames'), ('Survival', 'Survival'), ('Horror', 'Horror')], default=0, max_length=83),
        ),
        migrations.AddField(
            model_name='account',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=0, max_length=56),
        ),
        migrations.AddField(
            model_name='account',
            name='time',
            field=models.TextField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night'), ('Midnight', 'Midnight')], default=datetime.datetime(2022, 3, 13, 22, 55, 29, 808721, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 22, 55, 29, 809718, tzinfo=utc)),
        ),
    ]
