# Generated by Django 4.0.2 on 2022-03-18 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smg_app', '0002_alter_account_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='time',
            field=models.TextField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night'), ('Midnight', 'Midnight')], default=django.utils.timezone.now),
        ),
    ]
